# Generated by Django 5.0.4 on 2024-06-12 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Dars nomi')),
                ('video', models.FileField(help_text='Video yuklang', upload_to='lesson', validators=[django.core.validators.FileExtensionValidator('mp4,MOV')], verbose_name='dars nomi')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
