# Generated by Django 5.0.4 on 2024-06-12 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(help_text='Video yuklang', upload_to='lesson/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MP4,MOV'])], verbose_name='dars nomi'),
        ),
    ]
